######################################################################
# Automatically generated by qmake (2.01a) qua set 4 19:17:17 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += player.h
FORMS += player.ui
SOURCES += main.cpp player.cpp
RESOURCES += resource.qrc
